name: image_gallery
description: A Flutter plugin to fetch images from user gallery.
version: 0.0.1
author: Túlio Magalhães <tuliohdvp@gmail.com>
homepage: https://github.com/Tulioh/image_gallery

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: plugins.flutter.imagegallery
    pluginClass: ImageGalleryPlugin